stages:
  - build
  - deploy 


.podman-login:
  retry: 2
  before_script:
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"


podman-build-backend:
  stage: build
  extends: .podman-login

  image:
    name: quay.io/podman/stable

  script:
    - podman build -t "$CI_REGISTRY_IMAGE/ingame-api-backend:$CI_COMMIT_SHA" -t "$CI_REGISTRY_IMAGE/ingame-api-backend:latest"  .
    - podman push "$CI_REGISTRY_IMAGE/ingame-api-backend:$CI_COMMIT_SHA"
    - podman push "$CI_REGISTRY_IMAGE/ingame-api-backend:latest"

format:
  stage: deploy 
  when: always
  image: devth/helm:latest
  environment: production
  script:
    -  cd helm
    -  helm dependency update
    -  helm upgrade --install ingame-api-backend ./ --set image.tag=$CI_COMMIT_SHA --set image.repository=$CI_REGISTRY_IMAGE --create-namespace --namespace noway4u


