apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingame-api
  annotations:
    cert-manager.io/issuer: letsencrypt-prod  # Ensure this matches your ClusterIssuer or Issuer
spec:
  tls:
  - hosts:
    - ingame-api.salami.gg  # This is the alias you want
    secretName: ingame-api.salami.gg  # Secret where the certificate is stored
  rules:
  - host: ingame-api.salami.gg  # The host for the alias
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ingame-api-backend  # Replace with the name of your service
            port:
              number: 3000  # Port your service is listening on
