# templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingame-api 
spec:
  tls:
  - hosts:
    - ingame-api.salami.gg
    secretName: ingame-api.salami.gg
  rules:
  - host: "ingame-api.salami.gg"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "ingame-api-backend"
            port:
              number: 3000
      
